In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns',100)
pd.set_option('display.max_rows',100)

plt.style.use('dark_background')

# Without regex

In [2]:
file_path = '../../../Data/Text Processing/nh3.txt'

with open(file_path,'r') as f:
    lines = f.readlines()
# end

for line in lines:
    print(line, end='')

 ammonia, exp geometry, hf/sto-3g
GAUSSIAN              5 MOL ORBITALS     24 PRIMITIVES        4 NUCLEI
  N    1    (CENTRE  1)   0.00000000  0.00000000  0.20750474  CHARGE =  7.0
  H    2    (CENTRE  2)   0.00000000  1.79306401 -0.48417772  CHARGE =  1.0
  H    3    (CENTRE  3)   1.55283899 -0.89653201 -0.48417772  CHARGE =  1.0
  H    4    (CENTRE  4)  -1.55283899 -0.89653201 -0.48417772  CHARGE =  1.0
CENTRE ASSIGNMENTS    1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  2  2  3  3
CENTRE ASSIGNMENTS    3  4  4  4
TYPE ASSIGNMENTS      1  1  1  1  1  1  2  2  2  3  3  3  4  4  4  1  1  1  1  1
TYPE ASSIGNMENTS      1  1  1  1
EXPONENTS  0.9910617D+02 0.1805231D+02 0.4885660D+01 0.3780456D+01 0.8784966D+00
EXPONENTS  0.2857144D+00 0.3780456D+01 0.8784966D+00 0.2857144D+00 0.3780456D+01
EXPONENTS  0.8784966D+00 0.2857144D+00 0.3780456D+01 0.8784966D+00 0.2857144D+00
EXPONENTS  0.3425251D+01 0.6239137D+00 0.1688554D+00 0.3425251D+01 0.6239137D+00
EXPONENTS  0.1688554D+00 0.3425251D+01 

In [3]:
centers = []
for line in lines:
    check = line.strip().startswith('CENTRE')
    if check:
        centers.extend(line.split('ASSIGNMENTS')[1].strip().replace('  ',' ').split(' '))
    # end
# end

centers = np.array(centers).astype(int)
centers

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4,
       4, 4])

In [4]:
exps = []
for line in lines:
    check = line.strip().startswith('EXPONENTS')
    if check:
        exps.extend(line.split('EXPONENTS')[1].strip().replace('  ',' ').replace('D','e').split(' '))
    # end
# end

exps = np.array(exps).astype(float)
exps

array([99.10617  , 18.05231  ,  4.88566  ,  3.780456 ,  0.8784966,
        0.2857144,  3.780456 ,  0.8784966,  0.2857144,  3.780456 ,
        0.8784966,  0.2857144,  3.780456 ,  0.8784966,  0.2857144,
        3.425251 ,  0.6239137,  0.1688554,  3.425251 ,  0.6239137,
        0.1688554,  3.425251 ,  0.6239137,  0.1688554])

# With Regex

In [5]:
import re

In [6]:
with open(file_path,'r') as f:
    text = f.read()
# end

print(text)

 ammonia, exp geometry, hf/sto-3g
GAUSSIAN              5 MOL ORBITALS     24 PRIMITIVES        4 NUCLEI
  N    1    (CENTRE  1)   0.00000000  0.00000000  0.20750474  CHARGE =  7.0
  H    2    (CENTRE  2)   0.00000000  1.79306401 -0.48417772  CHARGE =  1.0
  H    3    (CENTRE  3)   1.55283899 -0.89653201 -0.48417772  CHARGE =  1.0
  H    4    (CENTRE  4)  -1.55283899 -0.89653201 -0.48417772  CHARGE =  1.0
CENTRE ASSIGNMENTS    1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  2  2  3  3
CENTRE ASSIGNMENTS    3  4  4  4
TYPE ASSIGNMENTS      1  1  1  1  1  1  2  2  2  3  3  3  4  4  4  1  1  1  1  1
TYPE ASSIGNMENTS      1  1  1  1
EXPONENTS  0.9910617D+02 0.1805231D+02 0.4885660D+01 0.3780456D+01 0.8784966D+00
EXPONENTS  0.2857144D+00 0.3780456D+01 0.8784966D+00 0.2857144D+00 0.3780456D+01
EXPONENTS  0.8784966D+00 0.2857144D+00 0.3780456D+01 0.8784966D+00 0.2857144D+00
EXPONENTS  0.3425251D+01 0.6239137D+00 0.1688554D+00 0.3425251D+01 0.6239137D+00
EXPONENTS  0.1688554D+00 0.3425251D+01 

In [7]:
centers = re.findall(r"CENTRE ASSIGNMENTS(.*)\n", text)
centers = [ re.findall(r"\d", m) for m in centers ]
centers = np.hstack(centers).astype(int)
centers

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4,
       4, 4])

In [8]:
exps = re.findall(r"EXPONENTS(.*)\n", text)
exps = [ re.findall(r"\S+", m) for m in exps ]
exps = np.hstack(exps)
exps = [ re.sub(r"D", r"E", m) for m in exps ]
exps = np.hstack(exps).astype(float)
exps

array([99.10617  , 18.05231  ,  4.88566  ,  3.780456 ,  0.8784966,
        0.2857144,  3.780456 ,  0.8784966,  0.2857144,  3.780456 ,
        0.8784966,  0.2857144,  3.780456 ,  0.8784966,  0.2857144,
        3.425251 ,  0.6239137,  0.1688554,  3.425251 ,  0.6239137,
        0.1688554,  3.425251 ,  0.6239137,  0.1688554])